### ISSUE TITLE
Show plot also for a single set

### ISSUE THREAD

**Issue by alexsb** [hms-dbmi/UpSetR-shiny#16]
When you only select one specific set, the view is empty: 

![image](https://cloud.githubusercontent.com/assets/2039375/12983097/fa469d60-d0a4-11e5-9e6e-88b28844c4c3.png)

A simple fix here would be to also show the plot only for one set.

**Comment by ngehlenborg** [comment]
I think a single set is not very interesting - we should require that at least two sets are entered.

**Comment by alexsb** [comment]
But it would give you some feedback that something is happening. I thought this "Select specific set" would highlight a specific set first, I didn't even realize that I could select multiple sets. 

So at a minimum, put a big message "Select at least two sets" in the main view.
