### ISSUE TITLE
configure travis for automatic deployment of successful builds

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/UpSetR-shiny#6]
A successful update (= build) of the master branch in the repo should be followed by an automatic update of the deployed Shiny app.

**Comment by JakeConway** [comment]
Am I able to do this if I don't have admin rights to the repository?

**Comment by ngehlenborg** [comment]
I might have to configure the commit hook in GitHub once you have set up the Travis tasks.

**Comment by ngehlenborg** [comment]
Closing because not practical.
